name: content-creation
description: End-to-end content production from research to publication

io:
  input_dir: input
  output_dir: output

variables:
  topic: ""  # Set via --topic flag or in input file
  target_audience: "freelance coaches and trainers"
  content_length: "1500-2000 words"

steps:
  - name: research
    skill: researcher
    input: ${topic}
    output: research_findings
    config:
      depth: comprehensive
      sources_required: 5
      include_statistics: true
  
  - name: strategy
    skill: strategist
    input: |
      Topic: ${topic}
      Research: ${research_findings}
      Audience: ${target_audience}
    output: content_strategy
    config:
      deliverable: content_brief
  
  - name: draft
    skill: author
    input: |
      Strategy: ${content_strategy}
      Research: ${research_findings}
      Target length: ${content_length}
    output: draft_content
    config:
      format: blog_post
      tone: professional
  
  - name: edit
    skill: editor
    input: ${draft_content}
    output: final_content
    config:
      review_type: comprehensive
      check_voice_consistency: true
      optimize_readability: true
